CFLAGS	= -g
CC	= gcc
OBJ	= myAllocatorTest1 test1 allocTest

all: $(OBJ)

myAllocatorTest1: myAllocator.o myAllocatorTest1.o
	$(CC) $(CFLAGS) -o $@ $^

test1: myAllocator.o myMalloc.o test1.o
	$(CC) $(CFLAGS) -o $@ $^

allocTest: allocTest.o myAllocator.o
	$(CC) $(CFLAGS) -o $@ $^

clean:
	rm -f *.o $(OBJ) 

